NCI-C4CP/connectFaas

utils/stats.js
Reverted metrics back to old tables. Query updated on google Big Query console.
Related PR: #9
=> Reverted metrics back to old tables

utils/stats.js
Added endpoints for Opt Outs, SSN, and Modules Survey endpoints.
Related PR: #124
=> [SiteManager Dashboard] Added Opt Outs, SSN Survey, and Survey Modules endpoints

utils/biospecimen.js, utils/firestore.js
-> Added POST & GET endpoint for Kit Assembly Data
Checklist:
**Notes:**
_**http://{URL}/stats?type=addKitData**_ returns success upon adding data to KIT ASSEMBLY collection
_**http://{URL}/stats?type=getKitData**_ returns entire complete collection from KIT ASSEMBLY
PoC:
GET
POST
=> BPTL Dashboard: Added Kit Assembly Endpoints

utils/firestore.js
This PR is used for debugging & fix errors.
=> [SiteManager Dashboard] Added console.logs

utils/biospecimen.js, utils/firestore.js
-> Added POST endpoint for shipped
Checklist:
**Notes:**
_**http://{URL}/biospecimen?api=shipped**_ updates & adds participant data with kit status, confirm pickup & date requested
=> BPTL Dashboard: Added Shipped API endpoint

utils/biospecimen.js, utils/firestore.js
=> BPTL Dashboard: Added minor changes

utils/biospecimen.js, utils/firestore.js
=> [BPTL Dashboard]: Added specimen usps tracking number to participant

utils/firestore.js
=> BPTL Dashboard: Destrucutured data response & added fallback for invalid scan for Package Receipt

utils/biospecimen.js, utils/firestore.js
* modified specimenExists() in firestorm.js to not update document if a match is found
* added "updateSpecimen" case to biospecimen.js
=> Update specimen function

utils/firestore.js
=> BPTL Dashboard: Added Date Withdrawn for CSV file report

utils/biospecimen.js, utils/firestore.js
-> Added UpdateBox API & Updated AddBox API endpoints
-> Edited BoxExists function to return only True or False
Checklist:
**Notes:**
_**http://{URL}/biospecimen?api=addBox**_ returns success if box is added
_**http://{URL}/biospecimen?api=updateBox**_ returns success if existing box is updated
=> Shipping Dashboard: Added UpdateBox API & Updated AddBox API

utils/biospecimen.js, utils/firestore.js
This PR addresses the following:
-> Change the parameter from siteAcronym to siteCode
-> Remove siteAcronym from db collection filter
-> Add another filter to db collection '789843387' key value equals siteCode
=> Shipping Dashboard: Change searchBoxes and searchBoxesByLocation

utils/biospecimen.js, utils/firestore.js, utils/shared.js
The removeBag() function was updated to handle new box structure.
=> Fixed remove bag()

utils/connectApp.js, utils/submission.js
* added API option for PWA endpoint to get participant biospecimen collections
=> added pwa api option

utils/firestore.js, utils/submission.js
* can't pass in site code with GET request
* need to fetch site acronym based on site code from participant record
=> fetching site acronym from uid

utils/firestore.js
- Add a way to update the containsOrphanFlag concept Id
=> Update contains orphan flag for remove bag

utils/biospecimen.js, utils/firestore.js, utils/shared.js
The PR addresses the following:
- Same as title
=> Change some references of siteAcronym to siteCode

utils/stats.js
- Added "participants_allModulesAllSamples" table in BQ
- Updated API to handle above table
=> Updated stats API

utils/firestore.js
=> SiteManager Dashboard: Updated getQueryBsiData concept ids

.gitignore, utils/firestore.js
Title ^^
PoC: '959708259 : "123456789123" in firestore boxes table
=> SiteManger Dashboard: Update Package Receipt function as per the new box structure

utils/firestore.js
=> BPTL Dashboard: Added nih/nci parent view option in BPTL- Packages In Transit

utils/biospecimen.js, utils/firestore.js
=> BPTL Dashboard: Added flag for BPTL searchBoxes API

utils/firestore.js
[#254](https://github.com/episphere/biospecimen/issues/254)
Related PR:
[#258](https://github.com/episphere/biospecimen/pull/258)
=> BPTL Dashbpard: Addressed csv issues

utils/firestore.js
=> BPTL Dashboard: added quick fix for CSV report

utils/firestore.js
=> BPTL Dashboard: Added date received timestamp instead of current timestamp & truncates 34 digit barcode scanner

utils/sites.js
Title^^
https://github.com/episphere/dashboard/issues/371
=> SiteManager Dashboard: First + Last Name in query field are defaulted to lower case when updated

utils/firestore.js
=> BPTL Dashboard: Replaced health care provider with collection location in CSV File

utils/firestore.js
Related PR:
https://github.com/episphere/connectFaas/pull/169
=> BPTL Dashboard: Added healthcare provider back in CSV Receipt

config/stage/cloudbuild3.yaml, config/stage/cloudbuild5.yaml
removed comments to enable NORC functions in YAML stage files
=> enabling NORC functions in stage

utils/firestore.js, utils/notifications.js, utils/sites.js
Changes include:
* enabling NORC API functions in stage
* first / last name lowercase 
* updates to setPackageReceiptFedex() function
=> Sync Stage w/ Dev 

utils/biospecimen.js, utils/shared.js, utils/submission.js
* removing locked attributes when checking for defaults
* moved logic, enabling BSD to use getUserProfile() used by PWA
=> Default variables check

utils/firestore.js
This PR addresses following issue.
In Create CSV file, the date query is performed on tube level to get more precise results.
https://github.com/episphere/biospecimen/issues/261
Related PR: #220
=> [BPTL Dashboard] CSV Revamp

config/prod/cloudbuild1.yaml, config/prod/cloudbuild3.yaml, utils/notifications.js
=> Stage / Dev Sync

utils/notifications.js
=> SM Dashboard: Added condition to skip HTML conversion for newsletter

utils/notifications.js
=> SM Dashboard: Removed HTML convertor temporarliy

utils/notifications.js
=> SiteManager Dashboard: Enabled showdown convertor in  Notification Handler

utils/notifications.js
* HTML Converter conditionality added for Newsletter
=> Stage / Prod Sync 082322

utils/sites.js
* first attempt at integrating consistency check into updateParticipant API
=> initial changes

utils/stats.js
=> SiteManager Dashboard: Added stats API entry for participants none modules

config/prod/cloudbuild1.yaml, config/prod/cloudbuild3.yaml, utils/biospecimen.js, utils/notifications.js, utils/sites.js, utils/submission.js
* Biospecimen API end-point added to check for Accession ID existence
* Logic updates to Notification pagination
* Baked QC logic into Update Participant Data API call (Sites)
=> Dev / Stage Sync 091422

utils/firestore.js
https://github.com/episphere/dashboard/issues/378
Replaced 'time recruitment type assigned' with 'verification status time'.
Related PR: https://github.com/episphere/dashboard/pull/431
=> SiteManager Dashboard: Filtration & Pagination date filter search update

utils/stats.js
Related PR: https://github.com/episphere/connectFaas/pull/248
=> SiteManager Dashboard: Added api entry for none modules

utils/sites.js
Reverts episphere/connectFaas#262
=> Revert "continue instead of break"

utils/sites.js
Reverts episphere/connectFaas#261
=> Revert "refactor"

utils/sites.js
Reverts episphere/connectFaas#260
=> Revert "restructure for loop"

utils/sites.js
Reverts episphere/connectFaas#259
=> Revert "bug"

utils/sites.js
Reverts episphere/connectFaas#258
=> Revert "initial changes to enable batching"

utils/sites.js
Reverts episphere/connectFaas#267
=> Revert "Revert "initial changes to enable batching""

utils/sites.js
Reverts episphere/connectFaas#266
=> Revert "Revert "bug""

utils/sites.js
Reverts episphere/connectFaas#264
=> Revert "Revert "refactor""

utils/sites.js
Reverts episphere/connectFaas#263
=> Revert "Revert "continue instead of break""

utils/firestore.js
https://github.com/episphere/biospecimen/issues/335
Related PR:
https://github.com/episphere/biospecimen/pull/416
=> BPTL Dashboard: Added clinical tubes for Clinical - CSV file

utils/firestore.js
Title^^
Related PR: https://github.com/episphere/connectFaas/pull/256
=> SiteManager Dashboard: Updated recruitment  date time with verification date time

utils/firestore.js
Title^^
https://github.com/episphere/biospecimen/issues/409
Related PR: 
https://github.com/episphere/connectFaas/pull/275
=> BPTL Dashboard: Updated condition for straggler/orphan tubes

utils/dashboard.js, utils/firestore.js, utils/validation.js
-> Built an API that checks for email or phone exists before signing in
-> Uses Firebase Auth built in functions (getUserByEmail, getUserByPhone) to find user with associated email or phone
=> ConnectApp: API to check if user exists using email or phone

utils/firestore.js
=> Connect App: updated function name getUserByPhoneNumber

utils/firestore.js
Title^^
Related PR: https://github.com/episphere/connectFaas/pull/282 https://github.com/episphere/connectFaas/pull/281 #238
=> Connect App: Included + operator

utils/firestore.js
Title ^^
Related PRs: #284 #283 #282 #281
=> ConnectApp: Slice last 10 digits of a phone number & append '+1' to the string 

utils/notifications.js
=> SiteManager Dashboard: Replaced connectid with Token for time tap

utils/events.js
Add more collections for backup.
=> BigQuery backup

utils/events.js
=> fix variable scope error

utils/validation.js
Reformatted if condition for if biospecimen exists.
Added && operators to if condition
=> [Notification Scheduler] Reformatted condition for if biospecimen exists

utils/firestore.js, utils/shared.js, utils/sites.js, utils/submission.js, utils/validation.js
connectApp
* added endpoint getUserSurveys
submission
* added function getUserSurveys
* added function submitSurvey
* added logic to call checkDerivedVariables() after survey completion
* added separate path for submit() if we are submitting survey answer data
firestore
* added function retrieveConnectID
* added function surveyExists
* added function storeSurvey
* added function updateSurvey
* added function retrieveUserSurveys
shared
* added constant moduleConceptsToCollections
* added constant moduleStatusConcepts
* added function cleanSurveyData
validation
* updated checkDerivedVariables to calculate derivation for enabling menstrual cycle survey
* added logic to not update participant if there isn't anything to update
=> changes for BQ fix

updateParticipantData.json, utils/biospecimen.js, utils/dashboard.js, utils/firestore.js, utils/shared.js, utils/sites.js, utils/submission.js, utils/validation.js
* Changes included to fix BQ issues
* Using token instead of Connect ID for Notifications
* Passing in correct Site Code for checking derived variables
=> Dev / Stage Sync 113022

utils/biospecimen.js, utils/validation.js
* checking derived variables when adding / updating biospecimen collections
* removed derivation calculation for any specimen collected at RRL
* added derivation calculation for all baseline surveys completed
=> Integrate derivations

utils/notifications.js
Title^^
Related PR: https://github.com/episphere/connectFaas/pull/298/files
=> SiteManager Dashboard: Revert timetap on utils/notifications

utils/notifications.js
=> SiteManager Dashboard: Replaced connectid with Token for time tap (in DEV)

utils/submission.js
Handle errors and undefined siteCode in  `getUserCollections` function.
=> Fix errors when calling getUserCollections()

updateParticipantData.json, utils/biospecimen.js, utils/firestore.js, utils/sites.js, utils/submission.js, utils/validation.js
- Added Biospecimen API call checkDerivedVariables
- Bug fix to properly set query.lastName
- Shifted await calls in updateParticipantData API call
- Added error handling in checkDerivedVariables() for null UID
- Removed derivation for "any specimen collected" in checkDerivedVariables()
- Added derivation for "all baseline surveys completed" in checkDerivedVariables()
- Added derivation for "blood and urine not refused" in checkDerivedVariables()
- Added derivation for "baseline order placed" in checkDerivedVariables()
- Added derivation for "clinical sample donated" in checkDerivedVariables()
- Added error handling in getUserCollections() for undefined site code
- Updated response code and object within accessionIdExists Biospecimen API call
=> January 2023 Dev / Stage Sync

utils/validation.js
This PR addresses issue https://github.com/episphere/connect/issues/615
* Added condition where we want to calculate value for CID 880794013
* Moved logic for Clinical Sample Donated inside same block as Baseline Order Placed
* Created helper function `checkSamplesDonated` for checking status of Clinical Sample Donated
=> Baseline Order Placed Logic Update

utils/firestore.js, utils/sites.js
This PR addresses bug caused by https://github.com/episphere/connectFaas/pull/322
* Needed to move `flat()` within scope of data object
* Removing `token` from data object after setting value to variable
* Added console log for troubleshooting clarity
=> Submit Participant API Bug Fix

package-lock.json, package.json
Reverts episphere/connectFaas#324
=> Revert "Dependencies upgrade"

utils/sites.js
This PR is an update to PR https://github.com/episphere/connectFaas/pull/322
* Added logic for scenario where sites don't send data with "state." prefix on data keys
=> Updates to Submit Participant API

utils/sites.js
This PR is an update to PR https://github.com/episphere/connectFaas/pull/330
* Adding success messages in response JSON for user clarity
* Bug fix referencing variables that expected to be state variables
=> Submit Participant API Updates

utils/validation.js
This PR is an update to https://github.com/episphere/connectFaas/pull/323
* Added scenarios where null values are present but we still want to re-calculate `880794013`
=> Baseline Order Derivation Update

.gitignore, utils/biospecimen.js, utils/firestore.js
This PR, together with frontend updates, is to solve issue [#625](https://github.com/episphere/connect/issues/625). Below are details:
- Made data updates atomic, by using batch
- Added `shipBatchBoxes` to handle batched boxes
- Cleaned up logics for data processing
=> Fix box finalization issue

utils/dashboard.js, utils/firestore.js, utils/sites.js
This PR addresses the following features:
-> Added API endpoint to switch login method from email to phone & vice-versa
-> Updated existing login method (email or phone)
Checklist:
**Notes:**
_**http://{URL}/dashboard?api=updateSignMechanism**_
=> SiteManager Dashboard: Added API endpoint for switch login mechanism

utils/dashboard.js, utils/firestore.js, utils/sites.js
=> [SiteManager Dashboard] Revert PR #341

utils/sites.js
Added detailed error fallback conditions for invalid phone numbers & email
Related issue: https://github.com/episphere/dashboard/issues/493
Related PR: https://github.com/episphere/dashboard/pull/523
=> SiteManager Dashboard: Detailed error feedback for switch login mechanism

utils/dashboard.js, utils/sites.js
This PR update previous implementations of [#493](https://github.com/episphere/dashboard/issues/493). Below are details:
- Fixed errors  in `updateUserAuthentication` API
- Restricted `updateUserAuthentication` API to only NIH and NORC users
- Cleaned up code for clarity
=> Fix bug and cleanup

utils/sites.js
This PR fixes an error in PR [#354](https://github.com/episphere/connectFaas/pull/354).
=> Fix acronym access error

package-lock.json, package.json, utils/biospecimen.js, utils/fieldToConceptIdMapping.js, utils/firestore.js, utils/shared.js
This cherry pick addresses the following issue:
- https://github.com/episphere/connect/issues/609
Related Pull Request: 
- https://github.com/episphere/connectFaas/pull/351
=> Biospecimen issue#609 cherry pick

utils/connectApp.js, utils/firestore.js
This PR adds an endpoint for logged-in connectApp users to update their firebase Authentication method in connectApp.
This is in continued support of [issue #635](https://github.com/episphere/connect/issues/635)
Supported login methods:
-email
-phone
Changes:
(1) Add reference to `updateUserFirebaseAuthentication` in `connectApp.js`
(2) Add `updateUserFirebaseAuthentication()` to `firestore.js`
=> Update connectFaas for connect app user editing

utils/biospecimen.js, utils/dashboard.js, utils/firestore.js, utils/submission.js, utils/validation.js
This PR address issue [#628](https://github.com/episphere/connect/issues/628). Below are details:
- Updated `searchSpecimen` API. It now returns response code 200 and an empty data object, when a biospecimen search returns no record
- Fixed a typo and add back a log in `dashboard.js`
=> Return code 200 when a collection is not found

utils/firestore.js
Title^^
https://github.com/episphere/connect/issues/588
Related PR:
https://github.com/episphere/biospecimen/pull/545
=> Biospecimen Dashboard: Added checkin filter to return list of checked in particpants

utils/dashboard.js, utils/firestore.js, utils/incentive.js, utils/shared.js
This PR addresses the following Issues:
* https://github.com/episphere/connect/issues/663
* https://github.com/episphere/connect/issues/664
Technical Changes:
* (Dashboard.js) - Removed option to authorize with site key
* (Firestore.js) - Removed function `validateSiteUser()`
* (Firestore.js) - Added `827220437` (Healthcare Provider) to return payload of `retrieveParticipantsEligibleForIncentives`
* (Firestore.js) - Updated function name and parameter name in `getChildrens()`
* (Shared.js) - Removed site key authorization checking from `APIAuthorization()`
* (Shared.js) - Added function `isDateTimeFormat()`
* (Incentive.js) - Refactored existing code
* (Incentive.js) - Added data checks on payload items
* (Incentive.js) - Added 206 return code option for data issues
=> Incentive API Updates

config/stage/cloudbuild3.yaml
This PR supports the following issues:
* https://github.com/episphere/connect/issues/664
Needed to uncomment a few lines from a YAML file to allow Cloud Function to build properly in stage
=> Stage YAML File Update

config/stage/cloudbuild3.yaml, utils/firestore.js
Related Sync PR:
Dev -> Stage Sync (July Release) https://github.com/episphere/connectFaas/pull/386
Needed to uncomment lines from YAML file to allow Cloud Function to build
=> Dev -> Stage Sync (July Release Part 2)

utils/sites.js
This PR addresses comment https://github.com/episphere/connect/issues/658#issuecomment-1672082286 of issue https://github.com/episphere/connect/issues/658
=> [#658] Refuse data sources for participant data destroyed

utils/biospecimen.js, utils/firestore.js
Title^^
https://github.com/episphere/connect/issues/631
Related PR:
https://github.com/episphere/biospecimen/pull/569
=> Biospecimen Dashboard: Added API endpoints to query participants for Daily Reports Page

utils/notifications.js
https://github.com/episphere/connect/issues/689#issuecomment-1692029999
Related PR:
https://github.com/episphere/connectFaas/pull/399
https://github.com/episphere/connectFaas/pull/405
=>  Notifications: Added else if clause for users with both email & phone login method (Part 3)

utils/notifications.js
=> print info for bug fix

utils/firestore.js, utils/shared.js
This PR addresses comment https://github.com/episphere/connect/issues/658#issuecomment-1692253548 of issue https://github.com/episphere/connect/issues/658
=> [#658] Remove notifications record that related to data destroyed

utils/bigquery.js
This PR fix a subtle bug in PR [#401](https://github.com/episphere/connectFaas/pull/401), by removing 'replaceAll' for string manipulation. 'replaceAll' isn't supported by our current node version 14.
=> 'replaceAll' not supported in node14

config/dev/cloudbuild2.yaml, config/prod/cloudbuild2.yaml, config/stage/cloudbuild2.yaml, index.js, utils/events.js
This PR backs up "notifications" collection in Firestore to BigQuery, as described in [#695](https://github.com/episphere/connect/issues/695).
Currently the backup occurs once per day.
=> backup notifications to BQ

utils/biospecimen.js, utils/firestore.js
Title^^
- Restricts Daily Reports Page to users sites
Related PR:
https://github.com/episphere/biospecimen/pull/582
=> Biospecimen Dashboard: Update Daily Reports Page API

utils/firestore.js, utils/shared.js, utils/submission.js
Addresses issue https://github.com/episphere/connect/issues/703
=> Ssn updates so that it acts like other surveys

utils/firestore.js
Title^^
- Returns Shipping Report data based on filters
- For BPTL, returns reports from all sites
- Optimized code as needed
Related PR:
https://github.com/episphere/biospecimen/pull/585
=> Biospecimen Dashboard: Update API endpoints to query Shipping Reports

utils/shared.js
This PR addresses the following Issues:
* https://github.com/episphere/connect/issues/737
-----
Background Details
* Adding new survey for At-Home Mouthwash collection
-----
Technical Changes
* added necessary constants in `shared.js`
=> Add Mouthwash Survey

utils/firestore.js, utils/shared.js
Found potential race condition in package receipt functions after adding new bags and streck tube.
This fixes the race condition and adds support for reading misc tubes 0050-0054.
=> Package receipt

utils/firestore.js, utils/shared.js
Late changes - biospecimen misc tubes in csv file - dev to stage sync
=> Dev -> Stage sync. Late changes (biospecimen misc tubes in csv file)

utils/incentive.js
Related Links
Issues: 
- https://github.com/episphere/connectFaas/pull/439
- https://github.com/episphere/connect/issues/806
PR related:
- https://github.com/episphere/connectFaas/pull/449
---
Problem: 
Need to expedite this code change from dev to stage.
Solution:
Created a new branch off of stage and sync remote changes. Cherry picked commit that was merged in dev.
---
Code Changes:
Cherry Pick commit from dev to stage to expedite testing
- https://github.com/episphere/connectFaas/pull/449
=> Cherry pick - NORC UChicago Incentive Eligible Participants API Test Commit (To Stage)

utils/firestore.js, utils/incentive.js
Related Links
Issues: 
- https://github.com/episphere/connect/issues/806
- https://github.com/episphere/connect/issues/740
PR related:
- https://github.com/episphere/connectFaas/pull/439
- https://github.com/episphere/connectFaas/pull/449
- https://github.com/episphere/connectFaas/pull/454
---
Problem: 
Need to expedite this UChicago Eligibility code change for NORC. 
Solution:
Created a new branch off of stage and sync remote changes. Cherry picked commit that was already merged in dev. Create normal PR to sync stage and prod.
**Note: The following stage to prod sync was made in preparation for a successful NORC API test. This is ready to sync when NORC testing in stage is successful. **
=> Stage -> Prod Sync (Expedite Incentive Eligibility API change for NORC)

utils/fieldToConceptIdMapping.js, utils/firestore.js
This PR addresses the following Issues:
* https://github.com/episphere/connect/issues/736
-----
Background Details
* Adding filter to getParticipants API for getting participants with birthday in a given month
-----
Technical Changes
* Added constant in `fieldToConceptIdMapping.js`
* Added IF statement to check for query key `birthMonth`
=> GetParticipants API Birth Month Filter

config/dev/.env.yaml, config/dev/cloudbuild2.yaml, config/prod/.env.yaml, config/prod/cloudbuild2.yaml, config/stage/.env.yaml, config/stage/cloudbuild2.yaml, index.js, package-lock.json, package.json, utils/firestore.js, utils/notifications.js, utils/sendGridEventWebhook.js
Reverts episphere/connectFaas#464
=> Revert "Revert "[#766] Move data from sendgrid to firestore""

utils/events.js
This PR addresses issue [#818](https://github.com/episphere/connect/issues/818), and code cleanup.
=> Sync 'kitAssembly' collection to BigQuery

utils/events.js
This PR syncs 'mouthwash_v1' data to BQ, as requested in issue [#825](https://github.com/episphere/connect/issues/825).
=> sync mouthwash data

utils/events.js, utils/firestore.js
Sync 'mouthwash_v1' data to BQ, as requested in issue [#825](https://github.com/episphere/connect/issues/825).
=> Dev -> Stage, late change (sync mouthwash data)

utils/fieldToConceptIdMapping.js, utils/firestore.js
Reverts episphere/connectFaas#457
=> Revert "GetParticipants API Birth Month Filter"

utils/events.js
This PR syncs `sendgridTracking` to BigQuery, as requested in issue [#835](https://github.com/episphere/connect/issues/835).
=> Sync 'sendgridTracking' to BigQuery

utils/events.js, utils/shared.js
This PR moves change in PR [#482](https://github.com/episphere/connectFaas/pull/482) from dev to stage, as requested in issue [#835](https://github.com/episphere/connect/issues/835).
The code change in PR482 was tested in dev and is ready for stage.
=> Dev -> Stage Late Change (sync sendgridTracking to BQ)

utils/firestore.js, utils/notifications.js, utils/sendGridEventWebhook.js
Call has been made to not include these changes in December Release
Issue: https://github.com/episphere/connect/issues/828
=> Revert "[#828] Move sendgrid data to notifications collection"

updateParticipantData.json
Reverts episphere/connectFaas#500
=> Revert "HOTFIX: Adding value to Update Participant Data Options"

utils/shared.js
This PR addresses comment https://github.com/episphere/connect/issues/640#issuecomment-1899265383
=> [#640] Keep data in KitAssembly collection

config/dev/.env.yaml, config/prod/.env.yaml, config/stage/.env.yaml, utils/notifications.js
Added environment variables for Twilio SMS messages. This PR tries to fix errors when building [PR#508](https://github.com/episphere/connectFaas/pull/508).
=> Add environment variables

utils/notifications.js
This PR fix a bug in calling async function at module level in [PR#516](https://github.com/episphere/connectFaas/pull/516)
=> fix async bug

updateParticipantData.json, utils/shared.js
https://github.com/episphere/connect/issues/675
Remove and disallow CID 457270069 'preliminary cancer stage information.'
This will likely be added back in the future, but it's no longer part of this release.
=> rca variables - remove and disallow 457270069

utils/notifications.js
This PR fixes new schema save issue in [PR#516](https://github.com/episphere/connectFaas/pull/516).
=> Return schema id after save

utils/sites.js
Related: https://github.com/episphere/connect/issues/864
Hotfix: write sequencing for updateParticipantData
=> hotfix updateParticipantData sequencing

utils/notifications.js, utils/sites.js
Hotfix: stage -> prod sync -> check derived variables sequencing fix
=> Stage - prod sync Hotfix  check derived variables sequencing fix

utils/notifications.js
This PR fix bugs, and also add error handling for message sending. This update follows [PR#508](https://github.com/episphere/connectFaas/pull/508).
=> Sms fixes and error handling

utils/notifications.js
This PR push new updates in dev to stage branch, for Jan release.
=> Dev -> Stage Late Update (Jan. Release) 

utils/notifications.js, utils/shared.js
Dev -> Stage sync - tighter timestamp validation
=> Dev -> Stage sync - tighter timestamp validation

utils/shared.js
Remove changes introduced in [#507](https://github.com/episphere/connectFaas/pull/507) and [#512](https://github.com/episphere/connectFaas/pull/512).
=> Remove cancerOccurrence destruction

utils/shared.js
Remove changes introduced in [#507](https://github.com/episphere/connectFaas/pull/507) and [#512](https://github.com/episphere/connectFaas/pull/512).
=> Dev -> Stage sync: data destruction

utils/shared.js, utils/sites.js
Dev -> Stage sync - update validation issue
=> Dev -> Stage sync - update validation issue

utils/shared.js, utils/sites.js
Stage -> Prod handle API validation fix
=> Stage -> Prod handle API validation fix

updateParticipantData.json, utils/shared.js, utils/sites.js
Dev -> Stage Sync - updateParticipantData array validation
=> Dev -> Stage Sync - updateParticipantData array validation

updateParticipantData.json, utils/shared.js, utils/sites.js
Stage -> prod sync updateParticipantData array validation
=> Stage -> prod sync updateParticipantData array validation

utils/bigquery.js, utils/firestore.js, utils/notifications.js
This PR:
- Implements code cleanups described in issue [#871](https://github.com/episphere/connect/issues/871)
- Improves query in BQ
- Improves error handling when retrieving notification schemas
=> Code cleanups and bug fixes

config/dev/.env.yaml, config/prod/.env.yaml, config/stage/.env.yaml, utils/connectApp.js, utils/submission.js
Related: https://github.com/episphere/connect/issues/900
Authenticate requests from GitHub API (raises limit from 60/hour to 5000/hour).
Use: SHA codes for survey modules.
=> authenticate to GitHub API

utils/firestore.js
This PR addresses issue https://github.com/episphere/connect/issues/886
=> [#886] Write error log for tracking

utils/notifications.js
This PR is related to issue [#886](https://github.com/episphere/connect/issues/886). It adjusts notification records saving, so that the records can be found and updated based on data from Twilio or SendGrid responses.
=> Save records timely

utils/firestore.js, utils/participantDataCleanup.js
This PR addresses issue https://github.com/episphere/connect/issues/636#issuecomment-1984579188
ChangeLog
- Add condition to remove participant:  The job removeUninvitedParticipants only removes participants with conditions
- pin is null
- token is null
- verificationStatus(821247024) is not verified(197316935)
=> [#636] Add condition to delete participant

utils/firestore.js, utils/sites.js
This PR addresses comment https://github.com/episphere/connect/issues/636#issuecomment-2007754040 of issue https://github.com/episphere/connect/issues/636
Code Changes:
Revert code
Update code in updateParticipantData to reject updaitng the uninvited flag if the participant is verified or The PIN was used to sign in
=> [#636] Reject to update the uninvited flag if the participant is verified or The PIN was used to sign in 

utils/promis.js, utils/submission.js
* https://github.com/episphere/connect/issues/870
-----
* We haven't received the credentials yet to the production PROMIS Scoring API server, temporarily commenting out code that would execute the logic.
-----
* Cleared values for `token` and `uoid`
* Commented out code to trigger PROMIS logic
=> PROMIS Scoring - Temp Revert

utils/fieldToConceptIdMapping.js, utils/sites.js
This PR addresses fix issue of https://github.com/episphere/connect/issues/636
=> Fix: update uninvited flag not working

config/dev/.env.yaml, config/prod/.env.yaml, config/stage/.env.yaml, utils/promis.js, utils/submission.js
* https://github.com/episphere/connect/issues/870
-----
* NIH PROMIS Server has been setup and we are ready to move previously tested logic into production
-----
* Removed temporary code comments in `submission.js`
* Added environment variables in dev, stage, and prod
* Updated PROMIS Scoring URL
* Obtaining PROMIS UOID and Token via GCP Secrets
=> PROMIS Scoring Update

utils/bigquery.js, utils/dashboard.js, utils/firestore.js, utils/notifications.js
Updates in this PR:
- add a new API to support dry run (test run) functionality for notification specs, as described in [discussion #934](https://github.com/episphere/connect/discussions/934)
- Implement [issue #943](https://github.com/episphere/connect/issues/943)
- add error handler in `storeNotificationSchema` function
- code cleanups
=> Add dry run support

utils/validation.js
This PR addresses issue https://github.com/episphere/connect/issues/959
=> [#959] Set any refusal or withdrawal to yes on data destruction

config/dev/.env.yaml, config/prod/.env.yaml, config/stage/.env.yaml, utils/promis.js, utils/submission.js
Reverts episphere/connectFaas#570 - Code is not ready for production until API can be reached via GCP
=> Revert "PROMIS Scoring Update"

utils/notifications.js
This PR addresses [issue #976](https://github.com/episphere/connect/issues/976) for the time being.
=> Handle mixed date types of "can we text"

config/prod/cloudbuild3.yaml, config/prod/cloudbuild4.yaml
This PR adjusts resources for notification sending and functionality (dry run, etc) in SMDB APIs.
=> Allow longer timeout

config/dev/cloudbuild2.yaml, config/prod/cloudbuild2.yaml, config/stage/cloudbuild2.yaml
Related: https://github.com/episphere/connect/issues/1009
getParticipants API: Boost memory allocation to support growing study and heavier use.
=> boost memory allocation: getParticipants API

updateParticipantData.json, utils/fieldToConceptIdMapping.js, utils/shared.js, utils/sites.js
Related: https://github.com/episphere/connect/issues/866
•Add new variables and validation to existing RCA Variables implementation.
=> RCA Variables -> add new variables

updateParticipantData.json
Reverts episphere/connectFaas#592
=> Revert "KP Prod Change 051024"

utils/fieldToConceptIdMapping.js, utils/shared.js
This pull request is related to:
- https://github.com/episphere/connect/issues/883
Code Changes:
Updated SSO config attributes (Values are still pending)
**Note: Having this pull request reviewable and ready after May release**
=> BSWH - connect faas add / update references

config/dev/cloudbuild3.yaml, config/prod/cloudbuild3.yaml, config/stage/cloudbuild3.yaml, index.js, utils/biospecimen.js, utils/fieldToConceptIdMapping.js, utils/firestore.js, utils/notifications.js, utils/shared.js
This PR:
- Implements scheduled notifications to handle English or Spanish as preferred language (issue [#918](https://github.com/episphere/connect/issues/918))
- Implements changed instant notification templates location to Firestore (issue [#968](https://github.com/episphere/connect/issues/968))
=> Spanish and instant notifications

updateParticipantData.json, utils/fieldToConceptIdMapping.js, utils/shared.js, utils/sites.js
Reverting because the site was not ready to test yesterday as we had hoped.
Reverts episphere/connectFaas#602
=> Revert "Revert "Revert "RCA Variables -> add new variables"""

utils/firestore.js
This PR addresses issue https://github.com/episphere/connect/issues/1034
ChangeLog
- Moved `const batch = db.batch();` inside the condition.
=> [#1034] Revert code

utils/connectApp.js, utils/firestore.js
Related: https://github.com/episphere/connect/issues/1048
-add `getAppSettings` to fetch Firestore `appSettings` properties
-add ConnectApp endpoint
NOTE: Merge with ConnectApp https://github.com/episphere/connectApp/pull/801
=> add getAppSettings endpoint

config/dev/.env.yaml, config/prod/.env.yaml, config/stage/.env.yaml
=> Update Secret Version

utils/notifications.js, utils/shared.js
This PR addresses issue https://github.com/episphere/connect/issues/1056
=> Spanish Translation of Email Signature for Notifications

utils/notifications.js, utils/shared.js
This PR addresses issue https://github.com/episphere/connect/issues/1057
=> Spanish Translation: magic link emails for login

utils/fieldToConceptIdMapping.js
This PR addresses issue https://github.com/episphere/connect/issues/1034
Added 100767870, 421823980 into stub variables list.
=> [#1034] Add new stub variables

config/dev/cloudbuild1.yaml, config/prod/cloudbuild1.yaml, config/stage/cloudbuild1.yaml, index.js, utils/biospecimen.js, utils/dashboard.js, utils/heartbeat.js, utils/incentive.js, utils/notifications.js, utils/shared.js, utils/sites.js, utils/stats.js, utils/submission.js, utils/validation.js
* N/A
-----
* Adding foundation for Connect Heartbeat API
-----
* Added new API end-point
* Updated YAML files
* Consolidated `require` statement for notifications in `index.js`
* Fixed spelling of function
=> Heartbeat API

utils/notifications.js, utils/shared.js
This PR addresses issue https://github.com/episphere/connect/issues/1057
=> [#1057] Type conversation

updateParticipantData.json, utils/fieldToConceptIdMapping.js, utils/shared.js, utils/sites.js
Reverts episphere/connectFaas#610
Removing RCA Variables from dev per Punchlist conversation on 7/22. It looks like this update is being pushed to August.
=> Revert "Revert "Revert "Revert "Revert "RCA Variables -> add new variables"""""

utils/shared.js
This PR addresses comment https://github.com/episphere/connect/issues/1056#issuecomment-2243888278
=> [#1056] Change text

updateParticipantData.json, utils/fieldToConceptIdMapping.js, utils/shared.js, utils/sites.js
Reverts episphere/connectFaas#626
Related: https://github.com/episphere/connect/issues/866.
Update: this has been requested for testing, so I'm getting it back into dev.
=> Revert "Revert "Revert "Revert "Revert "Revert "RCA Variables -> add new variables""""""

config/dev/cloudbuild3.yaml, config/prod/cloudbuild3.yaml, config/stage/cloudbuild3.yaml, index.js
Adjust settings for 2nd generation function deployment.
=> Adjust settings for function deployment

utils/shared.js
* N/A
-----
* NORC is changing SSO service providers and code updates are required on our end
-----
* Updated the value of `group` within the site constant `norcSSOConfig`
=> NORC SSO Updates

utils/notifications.js
Update cutoff time string based on time settings in spec.
=> Fix incorrect cutoff time string

utils/firestore.js
Removes erroneously included local configuration to run in local emulator which was causing build issues.
=> Reset erroneously included local configuration

utils/bigquery.js, utils/notifications.js
This PR addresses the issue of sending out MC survey reminders after 45-day window.
=> Block MC reminder after 45 days

utils/bigquery.js, utils/firestore.js, utils/notifications.js, utils/shared.js
Details in this PR:
- Support stop time for notifications, as requested in [issue#1112](https://github.com/episphere/connect/issues/1112)
- Upgrade handling of notification specification conditions, as requested in [issue#1064](https://github.com/episphere/connect/issues/1064)
- Some cleanups
=> Stop time and upgraded spec conditions handling

utils/bigquery.js
Update for [PR#654](https://github.com/episphere/connectFaas/pull/654), to handle possible OR conditions without parentheses.
=> Handle edge case

utils/firestore.js
Fixes a 500 issue found in testing for participant reset endpoint ([1084](https://github.com/episphere/connect/issues/1084)).
=> Added erroneously omitted FieldPath import

utils/firestore.js
This pull request is related to:
- https://github.com/episphere/connect/issues/1063
- https://github.com/episphere/connect/issues/1118
Code change: 
- update po box regex to handle "pobox" followed by optional digits.
=> Update regex for pobox filter

utils/shared.js
For Issue: https://github.com/episphere/connect/issues/1073
=> 2024 Connect Experience Survey

utils/shared.js
Fixes an issue found in testing
=> Updated experience2024 module ID

utils/events.js
This PR syncs "experience2024" collection to BigQuery, as requested in [comment here](https://github.com/episphere/connect/issues/1115#issuecomment-2384018916).
=> add "experience2024" collection

utils/notifications.js, utils/webhook.js
Fix error code 12300 in Twilio, as it doesn't prefer responses with JSON data.
=> Fix error code 12300 in Twilio

utils/biospecimen.js, utils/fieldToConceptIdMapping.js, utils/firestore.js, utils/validation.js
Reverts episphere/connectFaas#671
=> Revert "Added new endpoints and logic hardening for home mouthwash features."

utils/fieldToConceptIdMapping.js, utils/sites.js
THis PR addresses the comment of Madhuri
REF: https://github.com/episphere/connect/issues/1117
=> Fix: incorrect participant status

config/dev/cloudbuild5.yaml, config/prod/cloudbuild5.yaml, config/stage/cloudbuild5.yaml, index.js, utils/bigquery.js, utils/sites.js
This is for issue: https://github.com/episphere/connect/issues/1126
=> Initial Implementation of the getBigQueryData api call

utils/firestore.js, utils/validation.js
Fixes an issue saving participants if eligibilityUpdates are empty (discovered in testing.)
=> Review Collection Data Entry Error Fix

config/dev/.env.yaml, config/prod/.env.yaml, config/stage/.env.yaml, utils/connectApp.js, utils/validation.js
This PR addresses issue https://github.com/episphere/connect/issues/1149
=> [#1149] Sendgrid email address validation 

utils/dashboard.js, utils/firestore.js
This PR is related to the following links:
Issues
- https://github.com/episphere/connect/issues/1130
- https://github.com/episphere/connect/issues/1131
Feedback for SSN Survey Reset (Delete SSN document related to Participant)
- https://github.com/episphere/connect/issues/1130#issuecomment-2517731408
Code changes: 
- Changed update to a batch request to handle updating a participant's data in the participants collection and the ssn collection
- Renamed dateOfEligibility to dateOfEligibilityInput
=> Issue#1130 update ssn survey reset to batch

utils/firestore.js, utils/shared.js
Related: https://github.com/episphere/connect/issues/1134
We found bugs in the submitSpecimen routine, which was recently moved from Biospecimen to ConnectFaas.
This PR updates derivations in that routine: blood/urine/mouthwash collected variables and ensures consistency in the accessed data (rm found access to stale specimen data).
=> update submitSpecimen derivations and routine

config/dev/.env.yaml, config/prod/.env.yaml, config/stage/.env.yaml
Azure Registered App (NIH-NCI-DCEG-ConnectFirebase) client secret expires 12/29/2024, updating environment variables to point to new secret version
=> Secret Version Update

config/dev/cloudbuild1.yaml, config/dev/cloudbuild2.yaml, config/dev/cloudbuild3.yaml, config/dev/cloudbuild4.yaml, config/dev/cloudbuild5.yaml, config/prod/cloudbuild1.yaml, config/prod/cloudbuild2.yaml, config/prod/cloudbuild3.yaml, config/prod/cloudbuild4.yaml, config/prod/cloudbuild5.yaml, config/stage/cloudbuild1.yaml, config/stage/cloudbuild2.yaml, config/stage/cloudbuild3.yaml, config/stage/cloudbuild4.yaml, config/stage/cloudbuild5.yaml, package.json
Removing references to `episphere` after repository move to `NCI-C4CP`
=> URL Updates

utils/validation.js
Appears to be the cause of [1185](https://github.com/episphere/connect/issues/1185).
=> Fixed an issue where checkDerivedVariables was not appropriately awaiting an async function.

utils/validation.js
Dev-> Stage Sync: Cherry pick Home Mouthwash Collections Hotfix
Updated: `await` updates from `checkDerivedVariables` to resolve race condition in specimen form entry.
=> Dev-> Stage Sync: Cherry pick Home Mouthwash Collections Hotfix

utils/sites.js
We found an issue testing NORC Birthday Cards for the first prod push yesterday. It failed on withdrawn and data destroyed participants. That’s expected.
**Bug:**
It didn’t proceed beyond those withdrawn or data destroyed participants. So if the batch size was 100 participants, and the 25th participant had withdrawn status, 26-100 didn’t process.
I narrowed this to the updateParticipantData API’s `error` variable scope. It’s outside the participant data loop, so it doesn’t reset for each iteration of a multi-participant batch.
I was able to reproduce and resolve this behavior.
**Fix:**
•Track batch errors (whether there’s an error anywhere in the batch) to control the value returned (200 | 206). 
•Also track dataObj errors (that scope resets for each participant in the batch) to control …
=> updateParticipantData API - Update Error Scopes for NORC Birthday Cards

utils/sites.js
Dev -> Stage cherry-pick: updateParticipantData API - update error scopes
=> Dev -> Stage cherry-pick: updateParticipantData API - update error scopes

utils/sites.js, utils/validation.js
Stage -> Prod: cherry-pick: updateParticipantData API - update error scopes
=> Stage -> Prod: cherry-pick: updateParticipantData API - update error scopes

utils/firestore.js
* https://github.com/NCI-C4CP/connectFaas/security/code-scanning/1
* https://github.com/NCI-C4CP/connectFaas/security/code-scanning/2
* https://github.com/NCI-C4CP/connectFaas/security/code-scanning/3
* https://github.com/NCI-C4CP/connectFaas/security/code-scanning/4
* https://github.com/NCI-C4CP/connectFaas/security/code-scanning/5
* https://github.com/NCI-C4CP/connectFaas/security/code-scanning/6
* https://github.com/NCI-C4CP/connectFaas/security/code-scanning/7
* https://github.com/NCI-C4CP/connectFaas/security/code-scanning/8
* https://github.com/NCI-C4CP/connectFaas/security/code-scanning/9
* https://github.com/NCI-C4CP/connectFaas/security/code-scanning/10
* https://github.com/NCI-C4CP/connectFaas/security/code-scanning/11
* …
=> Code Scanning Fix

utils/firestore.js, utils/submission.js
Reverts NCI-C4CP/connectFaas#718
=> Revert "Dev -> Stage Sync (Code Scan Fix)"

utils/firestore.js
For [1067](https://github.com/episphere/connect/issues/1067)
=> Changed error messages per 1067 clarifications

utils/dashboard.js, utils/reports.js
For Issue: https://github.com/episphere/connect/issues/1163
=> Updated the smdb api for the physical activity report

utils/fieldToConceptIdMapping.js, utils/firestore.js
Ref: https://github.com/episphere/connect/issues/1179
=> [#1179] Data destruction for ROI PA

utils/firestore.js
Updated to validate assembled kits for duplicate tracking numbers and assigned kits for assignment to multiple participants ([1196](https://github.com/episphere/connect/issues/1196) and [1197](https://github.com/episphere/connect/issues/1197))
=> 1196 + 1197 Fixes

config/dev/.env.yaml, config/prod/.env.yaml, config/stage/.env.yaml, utils/connectApp.js, utils/shared.js, utils/validation.js
Ref: https://github.com/episphere/connect/issues/1190
=> [#1190] Implement api for usps validation

config/dev/getParticipantsDemo.yaml, index.js, utils/firestore.js, utils/submission.js
* N/A
-----
* Providing temporary end-point for sites to interact with new pagination logic
=> Get Participants (Demo)

config/dev/cloudbuild2.yaml, config/dev/getParticipants.yaml, config/prod/cloudbuild2.yaml, config/prod/getParticipants.yaml, config/stage/cloudbuild2.yaml, config/stage/getParticipants.yaml, index.js, utils/firestore.js, utils/submission.js
Removing `offset` functionality from `getParticipants` API
=> Get Participants API Refactor

utils/firestore.js
Updated to create a new biospecimen record for each home MW replacement kit
=> Home MW Biospecimen Generation Update

test/test.js, utils/firestore.js, utils/shared.js
Fixes an issue with participant whose addresses were changed to PO Boxes after initialization appearing in the print queue and never leaving
Fixes an issue with participants eligible for kit assignment being sorted incorrectly
=> Home MW Kit Fixes

utils/firestore.js
* Fixed issue where .data() was not getting called
* Sort order now from oldest to newest rather than newest to oldest
* Sort for replacement kits now uses date kit requested rather than bloodOrUrineCollectedTimestamp
* Addresses with PO boxes which have made it this far are no longer filtered out
=> Eligible participants sort updated per request

utils/bigquery.js, utils/stats.js
For Issue: https://github.com/episphere/connect/issues/1041
=> Added collection stats for the study manager dashboard

utils/firestore.js
=> Fixed an issue with an undefined variable.

utils/firestore.js
Sort order on CSV for replacement kits updated to match order on assign kits
=> Replacement Kit CSV Sort Order Update

utils/bigquery.js
Modified the queries to use _JP versions of the tables because the original tables only exist in dev.  For issue: https://github.com/episphere/connect/issues/1041
=> Updated the collection stats queries and processing

config/dev/biospecimen.yaml, config/dev/cloudbuild1.yaml, config/dev/cloudbuild2.yaml, config/dev/cloudbuild3.yaml, config/dev/cloudbuild4.yaml, config/dev/cloudbuild5.yaml, config/dev/dashboard.yaml, config/dev/incentives.yaml, config/dev/participantData.yaml, config/prod/biospecimen.yaml, config/prod/cloudbuild1.yaml, config/prod/cloudbuild2.yaml, config/prod/cloudbuild3.yaml, config/prod/cloudbuild4.yaml, config/prod/cloudbuild5.yaml, config/prod/dashboard.yaml, config/prod/incentives.yaml, config/prod/participantData.yaml, config/stage/biospecimen.yaml, config/stage/cloudbuild1.yaml, config/stage/cloudbuild2.yaml, config/stage/cloudbuild3.yaml, config/stage/cloudbuild4.yaml, config/stage/cloudbuild5.yaml, config/stage/dashboard.yaml, config/stage/incentives.yaml, config/stage/participantData.yaml
* N/A
-----
* Splitting Cloud Functions into their own YAML files to speed up Cloud Builds
=> Further YAML Separation

config/dev/.env.yaml, config/dev/scheduledSyncDHQ3Status.yaml, config/prod/.env.yaml, config/prod/scheduledSyncDHQ3Status.yaml, config/stage/.env.yaml, config/stage/scheduledSyncDHQ3Status.yaml, index.js, utils/connectApp.js, utils/dhq.js, utils/events.js, utils/fieldToConceptIdMapping.js, utils/firestore.js, utils/shared.js, utils/validation.js
DHQ III MVP implementation
Related: https://github.com/episphere/connect/issues/1238 & https://github.com/episphere/connect/issues/1305
• Implement initial DHQ API operations
• Implement DHQ credential allocation (Firestore)
• Implement scheduled function (will run nightly) to sync participant survey status (where survey status == started) with DHQ status, which is the source of truth in this implementation.
=> DHQ III MPV implementation

utils/firestore.js, utils/shared.js
* https://github.com/NCI-C4CP/connectFaas/security/code-scanning/15
-----
* Added function 'sanitizeObject()' to address security vulnerability
=> Code Scan Fixes

utils/firestore.js, utils/incentive.js
* https://github.com/episphere/connect/issues/1333
-----
* Updated information being sent to BSD to prevent data overwrite further up the chain
* Updated default limit in Incentives API to match current documentation
* Cleaned up function to using `token` consistently
=> Data Overwrite Bug Fix

.gitignore, utils/firestore.js, utils/incentive.js
Moving the following issues into stage early for testing:
* https://github.com/episphere/connect/issues/1222
=> Dev -> Stage Early Sync (July 2025 Release)

utils/firestore.js
* https://github.com/episphere/connect/issues/1345
-----
* Remove Firebase CIDs from API payload if participant hasn't consented
=> Credential Removal in Payloads

utils/firestore.js, utils/sites.js
Participant deceased checks for [1370](https://github.com/episphere/connect/issues/1370) now also check participantDeceasedNORC flag.
=> 1370 Followup

test/integration/dhq.integration.test.js, test/unit/dhq.test.js, test/unit/fileProcessing.test.js, utils/dhq.js, utils/fileProcessing.js, utils/notifications.js, utils/shared.js
Fix: https://github.com/episphere/connect/issues/1329
Issue found in production:
The 'Detailed Analysis' CSV is very large in prod. It's currently well over 100MB after decompression, and it will grow until the date flags are implemented. This was causing the V8 runtime to crash OOM.
Fix: 
• Replaced full CSV loading with CSV row-by-row streaming throughout.
• Memory cleanup of ZIP/CSV data after processing for GC access.
This allows processing extremely large CSVs in a memory-constrained environment.
Previously, memory was spiking during 'Detailed Analysis' processing and causing a crash.
The memory logs look steady after this streaming update:
=> DHQ Report data streaming

utils/firestore.js
Added additional default condition to processRequestAKitConditions to omit participants who have already had a mouthwash sample received.. Follow-up to stage testing for [1326](https://github.com/episphere/connect/issues/1326).
=> Default processRequestAKitConditions updated

utils/dashboard.js, utils/fileUploads.js
This PR implement requirements in [issue#1373](https://github.com/episphere/connect/issues/1373): 
- Migrate to signed URLs to handle large EHR files uploading
=> Use signed URLs

utils/dhq.js
Related: https://github.com/episphere/connect/issues/1446
DHQ API -- status sync -- control request speed.
Dev run log:
>  Found 1 participants to process.
>  Looking for DHQ completions since: 2025-04-02T19:15:20.280Z (180 days ago)
>  Found recent completions for study study_2944.
>  Found 1 studies with recent completions: [ 'study_2944' ]
>  Processing 1 participants in batches of 5 with 50ms delay between batches
>  Batch 1 completed. Success: 1, Errors: 0
>  DHQ Status Sync Summary: Total Found=1, Succeeded=1, Failed/Skipped=0
=> Update batch processing - DHQ Sync

utils/events.js, utils/shared.js
This pull request adds support for a new module, `preference2025`, across various configuration objects in `utils/shared.js`. The changes ensure that this new module is properly mapped for concept-to-collection relationships and status tracking.
**Support for new module `preference2025`:**
- Added `D_312845734` to the `moduleConceptsToCollections` mapping for `preference2025`.
- Added `692560814` to the `moduleStatusConcepts` mapping for `preference2025`.
- Included `preference2025` in the `listOfCollectionsRelatedToDataDestruction` array.
=> ROI Preference Survey
