NCI-C4CP/connectFaas

- .gitignore
- utils/bigquery.js
- utils/stats.js
This PR addresses the following features:
-> Stats API is extended, more info on notes. The API returns JSON response from Participant_Workflow, Participant_Verification, Participant_Recruits_Count DB.
Checklist:
**Notes:**
_**http://{URL}/stats?type=participants_workflow**_ returns cumulative or current workflow
_**http://{URL}/stats?type=participants_verification**_ returns verification status of the users
_**http://{URL}/stats?type=participants_recruits_count**_ returns active or passive recruits count
**Test cases:**
**-> participants_recruits_count for SITE A:**
**-> participants_recruits_count for SITE B:**
> Added routes for stats API

- .gitignore
- utils/stats.js
This PR addresses the following features:
-> Stats API for metrics is updated to a new tables. The API returns JSON response from `participants_race_by_siteCode, participants_age_by_siteCode, participants_gender_by_siteCode
`
Checklist:
**Notes:**
_**http://{URL}/stats?type=race**_ returns race response
_**http://{URL}/stats?type=age**_ returns age response
_**http://{URL}/stats?type=sex**_ returns gender response
**Test cases:**
**-> Age response for SITE A:**
**->Age response for SITE B:**
> Updated Metrics Table

- utils/biospecimen.js
- utils/firestore.js
-> Added POST & GET endpoint for Participant Selection
Checklist:
**Notes:**
_**http://{URL}/biospecimen?api=printAddresses**_ returns success upon adding participant data to Participant Selection collection
_**http://{URL}/biospecimen?api=getParticipantSelection&type=${filter}**_ returns participant data with kit status set as per  filter
_**http://{URL}/biospecimen?api=assignKit**_ updates participant data with kit status, usps tracking number & supply kit id
> BPTL Dashboard: Added Participant Selection APIs

- utils/biospecimen.js
- utils/firestore.js
-> Added POST endpoint for package receipt
-> Added GET endpoint for bptl metrics
Checklist:
**Notes:**
_**http://{URL}/biospecimen?api=storeReceipt**_ stores package receipts information for participants
_**http://{URL}/biospecimen?api=bptlMetrics**_ returns BPTL metrics
>  BPTL Dashboard: Added endpoints for package receipt & bptl metrics

- utils/biospecimen.js
- utils/firestore.js
-> Added GET endpoint for BPTL metrics
-> Endpoint returns list of participants with kit status = shipped
Checklist:
**Notes:**
_**http://{URL}/biospecimen?api=bptlMetricsShipped**_ returns list of participants with kit status = shipped
> BPTL Dashboard: Added BPTL Metrics API endpoint

- utils/biospecimen.js
- utils/firestore.js
- utils/shared.js
-> Added GET endpoint for BPTL BSI endpoint
-> Endpoint returns BSI data which is stored in CSV file
Checklist:
**Notes:**
_**http://{URL}/biospecimen?api=queryBsiData**_ returns list of participants with kit status = shipped
> BPTL Dashboard: Added BSI endpoint & modified setPackageReceiptFedex

- utils/notifications.js
This PR addresses following TimeTap issue:
Removed html markdown <> and used ${} for connect_id
> SiteManager Dashboard: TimeTap

- utils/biospecimen.js
- utils/firestore.js
There was a bug with the previous code that was adding another document instead of updating the existing one. The following changes were made:
* created updateSpecimen() function in firestorm.js - this function has the code that we previously deleted from specimenExists() where it updates the collection snapshot
* in the updateSpecimen case on biospecimen.js if we return true on specimenExists() then we call the new updateSpecimen() function instead of the storeSpecimen() function which would create a new record
> bug fix to update doc instead of add another

- utils/biospecimen.js
- utils/firestore.js
This pull request addresses the following:
- Change snapshot to target siteCode instead of siteAcronym to handle new box structure
Notes:
http://{URL}/biospecimen?api=ship 
An Example of the [POST] body
```
{
"boxes": ["Box3"],
"shippingData":{
"105891443": "Box3",
"666553960": "712278213",
"885486943": "Barra",
"948887825": "Gene"
},
"trackingNumbers":{
"Box3":"123456789012"
}
}
```
> Change query parameter to siteCode

- utils/firestore.js
https://github.com/episphere/connect/issues/548
Previous code logic created race conditions which stored inconsistent data across Firestore collection.
Updated code logic prevents race conditions & optimized to provide consistent data
> BPTL Dashboard: Addressed Package Receipt bug fix

- utils/firestore.js
-> Prevent duplicate tube records
-> Optimized CSV receipts data process on query level
> BPTL Dashboard: Optimized query on tube level & prevent duplicate record

- utils/biospecimen.js
Title^^
When accession ID doesn't exist returns error code 400 and in turn terminates the process on the clinical dashboard
> Clinical Dashboard: Enhanced error handling accessionIdExists api

- utils/firestore.js
- utils/shared.js
- utils/submission.js
- utils/validation.js
This PR is to fix issue https://github.com/episphere/connect/issues/604
* Added condition in `getParticipants` to retrieve participants based on either a default search criteria or one that can be passed into the API as an option
* New condition utilizes new shared constant `refusalWithdrawalConcepts` that defines the option names and corresponding Concept ID
* New condition utilizes new Firestore function `retrieveRefusalWithdrawalParticipants` that builds and runs the query to retrieve the appropriate participant data
* Added logic to `checkDerivedVariables` to calculate new derived variable `anyRefusalWithdrawal` (Concept ID 451953807) which is used as a default option for new `getParticipants` functionality
* Added function `checkRefusalWithdrawals` to calculate value of …
> Adding Refusal / Withdrawal Type to getParticipants API

- utils/submission.js
This PR is a small update to PR https://github.com/episphere/connectFaas/pull/321
* Adding `limit` and `dataSize` parameters to response object of `refusalswithdrawals` type within `getParticipants` API in order to match the structure of other types within the same API
> Add Response Parameters to Refusal / Withdrawal API

- package-lock.json
- package.json
This PR compiles dependabot PRs for dependency updates, except express-4.18.2 and minimist-1.2.8 because of merge conflicts. 
The conflicts in the 2 updates (express-4.18.2 and minimist-1.2.8) need to be resolved and tested before merging to dev branch.
> Dependency updates from dependabot PRs

- utils/firestore.js
_"On switch from phone to email and upon signin. It doesnt give you magic link but asks user for password."_
Related PR:
https://github.com/episphere/connectFaas/pull/341
https://github.com/episphere/connectFaas/pull/346
Related issue: episphere/dashboard#493
> SiteManager Dashboard: Fix phone to email magic link

- updateParticipantData.json
- utils/sites.js
This PR resolves issue https://github.com/episphere/connect/issues/639
* Add new keys to `updateParticipantData.json`
* Add rules to `qc()` to allow value types of `array` to be accepted
* Arrays must contain only string objects
* Preventing flattening of keys with values of type `array` when flattening new data
> Enabling Array Payloads - Update Participant Data API

- utils/dashboard.js
Add `updateParticipantDataNotSite()` to `dashboard.js`
This step is connected to [issue #635 ](https://github.com/episphere/connect/issues/635) to allow editing of user data by a logged-in user in SMDB. This will allow calling the `updateParticipantDataNotSite` endpoint from SMDB, which, in turn, processes the new data submission.
> add updateParticipantDataNotSite to dashboard.js

- utils/firestore.js
This PR adresses a issue that SMDB can not look up participant who removed data destruction
- Renamed variable `dataDestructionFieldList` to `stubRecordList`
- Added `state` `371067537`  `827220437` into `stubRecordList`
> Bug Fix - Participant data cleanup remove stub records

- utils/biospecimen.js
- utils/firestore.js
This PR addresses following issue https://github.com/episphere/biospecimen/issues/426:
Originally users could lookup only NIH specimens. Moving forward BPTL users can
search for specimens using collection ID from different sites.
Related PR: https://github.com/episphere/biospecimen/pull/536
> BPTL Dashboard: Enable collection search across all sites for BPTL users

- utils/firestore.js
This PR is in support of https://github.com/episphere/connect/issues/654 - expand name search.
Update the `filterDb()` function to handle both string and array<string> fields for participant search fields `query.firstName` and `query.lastName`.
If `name` is included in the `query`, we have to handle two cases: sometimes `typeof(participantDoc.query.firstName) === 'string'` and sometimes `typeof(participantDoc.query.firstName) === 'array'`.
•If it's a string, we can just do a simple `query.where('query.firstName', '==', queries.firstName.toLowerCase())`.
•If it's an array, we have to do a `query.where('query.firstName', 'array-contains', queries.firstName.toLowerCase())`.
The caveat to `array-contains` searches: we can only have one `array-contains` per query. So, when multiple …
> Expand name search for query.firstName and query.lastName arrays

- utils/connectApp.js
- utils/fieldToConceptIdMapping.js
- utils/firestore.js
- utils/validation.js
This PR implements backend code for issue [#659](https://github.com/episphere/connect/issues/659), with some code cleanup. Below are details:
- Moved error handling to API level, for code simplicity
- Added duplicate flag check when verifying token and pin
- Moved common logic for token and pin checks to `verifyTokenOrPin`, to eliminate repeated code, based on comment from Abhinav
- Retired `verifyToken` and `verifyPin` functions, based on comment from Tony
> Implement duplicate account label check

- utils/firestore.js
PR: Handle name search case sensitivity.
This is a small update to:
https://github.com/episphere/connectFaas/pull/381
It is in continued support of:
https://github.com/episphere/connect/issues/654
Issue: the query names were being forced to lowercase (desired behavior), but the results filter was filtering based on the original query. This caused lowercase searches to succeed and searches with uppercase characters to fail.
Update: Check for firstName, lastName, and email at the beginning of function execution and convert any/all to lowercase. This improves upon converting the query string to lowercase and then converting the filter to lowercase.
> handle name search case sensitivity

- utils/firestore.js
https://github.com/episphere/connect/issues/676
As the title suggests, multiple concurrent calls to `processReceiptData()` have led to data inconsistencies when performing writes/updates. To prevent race conditions in a simpler way, we can initialize mutex as an instance of a resolved promise.
The goal here is that every time the function `processReceiptData()` is invoked, we are effectively "queueing" the execution of the code. For the first call, our initial instance of the mutex promise is a resolved promise, so the code will be executed straight away on the next cycle of the event loop.
Calling .then() on a promise returns a new promise instance that is used to replace the original mutex instance. This new promise instance is also returned by the `processReceiptData() `function.
This …
> BPTL Dashboard: Added mutex to prevent race condition in Package Receipt

- utils/firestore.js
Related issue: https://github.com/episphere/connect/issues/654
Cleanup from July release:
We previously supported string and array search for `query.firstName` and `query.lastName` variables in the participant profile. Those have since been converted to arrays. This PR:
•removes string support for search (this saves one query for single name search and 2 queries for full name search).
•uses Promises.all() for query execution when multiple 'array-contains' searches are included (firstName, lastName, phone, email).
I updated comments to reflect the new search structure and removed references to string support for name search.
> Remove string support in name search

- utils/notifications.js
- utils/shared.js
https://github.com/episphere/connect/issues/689
When notifications (esp. emails) are sent out for users with both email & phone login method. The `<loginDetails>` in email is shown as undefined. To prevent this added else if clause to capture users with both login methods.
- Modularized functions that redact email & phone. 
- Returns following statements:
Email Login: `Your login information for the MyConnect app is ` + `email` + `.`;
Phone Login: `Your login information for the MyConnect app is` + `phone` + `.`;
Both Email & Phone Login: `Your login information for the MyConnect app is ` + `email` + `or` + `phone` + `.`;
PoC:
Used a workaround to see how the text renders:
Phone:
Email:
Both Phone & Email:
> Notifications: Added else if clause for users with both email & phone login method

- utils/firestore.js
- utils/shared.js
This PR addresses comment https://github.com/episphere/connect/issues/658#issuecomment-1684110577 from issue https://github.com/episphere/connect/issues/658.
- Added function `removeDocumentFromCollection` to delete all data that relates to participant data destruction from these collections `"bioSurvey_v1", "clinicalBioSurvey_v1", "covid19Survey_v1", "menstrualSurvey_v1", "module1_v1", "module1_v2", "module2_v1", "module2_v2", "module3_v1", "module4_v1", "ssn", "biospecimen"`
> [#658] Delete data from surveys and speciments

- utils/biospecimen.js
- utils/fieldToConceptIdMapping.js
- utils/firestore.js
Update handling for new box creation in the Biospecimen shipping dashboard.
Related: https://github.com/episphere/connect/issues/685
Previously, boxIds were generated by getting all boxes for a site, iterating them, finding the highest boxId, and incrementing by one.
Now, we're switching to a more efficient method:
`getSiteMostRecentBoxId` gets the site's `docId` and `mostRecentBoxId` from the `siteDetails` collection.
`docId` is used to access and update the firestore doc.
`mostRecentBoxId` will be incremented client-side and updated on box creation with `addBoxAndUpdateSiteDetails`. 
`addBoxAndUpdateSiteDetails` performs a batch operation to:
(1) Create a new box in the `boxes` collection, and
(2) Log that box's id as a numeric value in the site's doc in the `siteDetails` collection for …
> addBoxAndUpdateSiteDetails, getSiteMostRecentBoxId

- utils/firestore.js
Title^^
https://github.com/episphere/connect/issues/631
- Fixed logic for Participants record that need to be removed from the table after 2 days of check-in
Related PR:
https://github.com/episphere/biospecimen/pull/569
Logic Evaulation:
```
Check In Date, '>=', twoDaysAgo from current date
22 aug          >=     20 aug
22 aug           >=    21 aug
22 aug          >=     22 aug
22 aug   !== 23 aug // record removed from the table
```
> Biospecimen Dashboard: Added API endpoints to query participants for Daily Reports Page (Part 2)

- utils/bigquery.js
- utils/notifications.js
This PR fix bugs in PR [#401](https://github.com/episphere/connectFaas/pull/401). Below are details:
- Avoids using variables (firstNameField, preferredNameField, emailField) when not available in some notification specifications
- Handles BQ errors when occurred
- Put back `participantTokenArray` updates
- Other small things
These updates were tested locally with no problems found.
> bux fixes on PR#401

- utils/firestore.js
This PR addresses comment https://github.com/episphere/connect/issues/658#issuecomment-1697585534 of issue https://github.com/episphere/connect/issues/658
**Reason**: Using
```
while (listOfCollectionsRelatedToDataDestruction.length > 0) {
const collection = listOfCollectionsRelatedToDataDestruction.shift();
```
=> `listOfCollectionsRelatedToDataDestruction` will be empty once running to the second participant.
**Solution** Using `for (const collection of listOfCollectionsRelatedToDataDestruction)` instead.
> [#658 - Bug Fix] Not working if there are more than 2 participants

- utils/biospecimen.js
- utils/firestore.js
Related: https://github.com/episphere/connect/issues/685
Issue: We found a logic flaw in the existing `removeBag` function in ConnectFaas. An error in the iteration logic was causing bag overwrite depending on the position of the removed bag. This resulted in multiple bags being removed from a box in certain cases. This behavior was first brought up by a lab worker at HP 2 months ago and was reconfirmed in testing.
This function updates bag removal handling and adds error handling.
(1) Remove specified bag(s).
(2) Create new sortedBox.
(3) Iterate old box, placing foundKeys in order in the new sortedBox (Thing 1, Thing 2, Thing 3, etc...).
(4) Copy remaining keys to sortedBox and update firestore.
> fix logic error in removeBag. Add error handling.

- config/dev/cloudbuild2.yaml
- config/prod/cloudbuild2.yaml
- config/stage/cloudbuild2.yaml
- utils/bigquery.js
This PR improves [PR#415](https://github.com/episphere/connectFaas/pull/415)(for issue [#695](https://github.com/episphere/connect/issues/695)) and [PR#401](https://github.com/episphere/connectFaas/pull/401)(for issues [#692](https://github.com/episphere/connect/issues/692)). Below are details:
- Use a new scheduler in each tier for notifications backups
- Handle future new notification specifications when doing BQ queries
> Use new scheduler and handle future specs

- utils/firestore.js
Title^^
- Returns an empty array when they're no participants to check-in. This prevents the UI form breaking on load.
Related PR:
https://github.com/episphere/biospecimen/pull/569
https://github.com/episphere/connectFaas/pull/403
> Biospecimen Dashboard: Update API endpoints to query participants for Daily Reports Page

- utils/biospecimen.js
- utils/firestore.js
- utils/shared.js
Related: https://github.com/episphere/connect/issues/708
Adding endpoints: `getSpecimensByCollectionIds` and `getSpecimensByReceivedDate`
•`getSpecimensByReceivedDate` allows us to query specific boxes and then query only the specimens in those boxes. This will be used in the BPTL dashboard.
•`getSpecimensByCollectionIds` is a helper to `getSpecimensByReceivedDate` and is added as an endpoint for separate specimen search functionality.
> add getSpecimens: ByCollectionIds & ByReceivedDate

- utils/biospecimen.js
- utils/firestore.js
Related Links:
[Phase 2 Enhancements](https://github.com/episphere/connect/issues/708) 
[Issue#548](https://github.com/episphere/biospecimen/issues/548)
[Related biospecimen PR#586](https://github.com/episphere/biospecimen/pull/586)
[Related connectFaas PR#431](https://github.com/episphere/connectFaas/pull/431) 
This PR addresses the 500 status code returned on BPTL's packages in transit
The following code changes were done:
- moved return `collectionIdArray` in getBiospecimenCollectionIdsFromBox function outside of `for (let key in shipBoxObj) {...}` block
- fixed incorrect concept id reference to `orphanScan` variable (was incorrectly referencing biohazardMouthwashBagScan)
Images:
**Status code: 500**
**Local Tests**
> Fix searchSpecimenBySiteAndBoxId function

- utils/validation.js
This PR is related to the following links:
Issue: 
- https://github.com/episphere/connect/issues/740
PR related: 
- https://github.com/episphere/biospecimen/pull/599
---
Issue#740 
Problem: 
- University of Chicago Participants are currently excluded from 'NORC Incentive Eligible' at baseline.
Solution: 
- Removed logic where uChicago participants are excluded from NORC payment eligibility
---
Code Changes: 
- Removed ternary operator logic that checked if data object's Healthcare Provider(827220437) was University of Chicago (80970386) and assigns No (104430631) value to incentiveUpdates's `130371375.266600170.222373868` key
- `130371375.266600170.222373868` key value will now be assigned Yes (353358909), regardless of Healthcare Provider
> Add NORC incentives for Chicago participants

- utils/firestore.js
Fix error in tube to conceptId mapping on shipment receipt.
This function updates the received status of tubes.
We added support for misc tubes 0050-0054, but there was a bug in the mapping. Previously, I mapped them to tubeID (0001-0024).
This update maps to conceptId so the function can update received status based on that conceptId.
This function impacts the receipted csv, since that operation pulls tubes based on each tube's received status and timestamp.
> fix misc tube csv mapping

- utils/incentive.js
This PR is related to the following links:
Issues: 
- https://github.com/episphere/connectFaas/pull/439
- https://github.com/episphere/connect/issues/806
---
Issue#740 
Problem: When NORC used the [Get Participants Eligible for Incentive API Endpoint](https://documenter.getpostman.com/view/7490604/SVYnT26j#783e2fea-a8f8-4887-90e2-1b0c62e2fae5) to get University of Chicago incentive eligible participants, one of the two test participants should have appeared.
Solution: 
Removed conditional removing University of Chicago concept Id from `sitesCodes` array. 
---
Code Changes: 
Removed conditional removing University of Chicago concept Id (809703864) from `sitesCodes` array. In the `retrieveParticipantsEligibleForIncentives` function University of Chicago is now added to the sites that can be …
> Add University of Chicago Incentive Eligible Participants to appear for NORC

- config/dev/.env.yaml
- config/prod/.env.yaml
- config/stage/.env.yaml
- index.js
- package-lock.json
- package.json
- utils/firestore.js
- utils/notifications.js
- utils/sendGridEventWebhook.js
This PR address issue https://github.com/episphere/connect/issues/766
- Added the keyName of GCP Secret-Manager that is storing the verification keys of the sendgrid event webhook  into env files.
- Added endpoint `sendGridEventWebhook` for the sendgrid event webhook
- Installed package `@sendgrid/eventwebhook` to verify  the sendgrid event webhook verification key.
- Added `custom_args` to send email parameters to send some data (connect_id, notification_id, token) to sendgrid. We will get it back while receiving data from event webhook
- Added function `processEventWebhook` in firestore.js for processing data that received from event webhook
> [#766] Move data from sendgrid to firestore

- utils/firestore.js
- utils/notifications.js
- utils/sendGridEventWebhook.js
This PR addresses issue https://github.com/episphere/connect/issues/828
The data in `notifications` collection will be as image below
> [#828] Move sendgrid data to notifications collection

- updateParticipantData.json
- utils/fieldToConceptIdMapping.js
- utils/shared.js
- utils/sites.js
Issue: https://github.com/episphere/connect/issues/823
Update the updateParticipantData API for:
(1) deceased data: 2 new data points + one derived data point per issue 823.
Note: the deceased data is currently ignored if submitted and deceased = no.
(2) user profile archiving: This API needs to handle user profile archiving the same way ConnectApp and SMDB handle archiving.
(3) participant profile query arrays handling: Similarly, we need to handle the participant 'query' arrays (first name, last name phone, email) the same way it's handled in SMDB and ConnectApp to ensure consistent participant search functionality across our apps (Biospecimen & SMDB search functions).
> deceased data

- utils/biospecimen.js
- utils/fieldToConceptIdMapping.js
- utils/firestore.js
- utils/shared.js
Update the `storeReceipt` endpoint along with `setPackageReceiptFedex()`
**Important:** merge concurrently with https://github.com/episphere/biospecimen/pull/633
Related Issues:
Missing tube timestamps: https://github.com/episphere/connect/issues/819 & https://github.com/episphere/connect/issues/653
Duplicate tracking number: https://github.com/episphere/connect/issues/834
Related PRs:
https://github.com/episphere/biospecimen/pull/633
-add communication with BPTL user when unusual package receipt situations arise (duplicate tracking numbers & already received packages).
-batch process box and specimen receipt to ensure database consistency (solve missing tube timestamps issue).
-update error handling so we have a better trace if issues persist.
-change endpoint name to …
> update BPTL specimen package receipt processing

- updateParticipantData.json
- utils/sites.js
Requirements changed: ISO 8601 timestamp CID 772354119 is now optional.
> update per changed requirements

- updateParticipantData.json
NOTE: This code is only temporary.
HP needs to correct dates for a large batch of participants and we don't allow that field to be updated with the Update Participant API. Adding the Concept ID to list of accepted values while Vijay sends the correct data. This PR will be reverted once the changes are done.
> HOTFIX: Adding value to Update Participant Data Options

- utils/biospecimen.js
- utils/firestore.js
Add getSpecimenAndParticipant endpoint
Related issue: https://github.com/episphere/connect/issues/833
Related PR:
Note: Merge with Biospecimen PR
-Return specimen and participant data in one operation instead of separate calls.
-Used in collection ID search -> collection data entry form.
-Continued migration away from `searchSpecimen()` catch-all endpoint.
> Get Specimen and Participant

- utils/fieldToConceptIdMapping.js
- utils/sites.js
Issue: https://github.com/episphere/connect/issues/856
New death data requirement:
Add participation status -> deceased to EMR death data update via updateParticipantData API.
This update sets 912301837 (participation status) to the value 618686157 (deceased) when EMR death data is sent through the updateParticipantData API.
> new requirement: death data -> update participation status to deceased

- utils/shared.js
This PR addresses comment of PR https://github.com/episphere/connect/issues/640#issuecomment-1896266558
- Remove all related data of participant that has been destroyed data in 2 tables kitAssembly, cancerOccurrence
> [#640] Delete related data of new tables after running data destruction

- utils/submission.js
This PR addresses a bug from the following Pull Request:
* https://github.com/episphere/connectFaas/pull/499
-----
* Keys from request object are being deleted prior to checks on the length of the request
-----
* Moved `delete` statements in `submission.js`
> PR 499 - Bug Fix

- utils/notifications.js
This PR fix errors caused by missing email addresses, when sending emails.
This PR is related to [issue#827](https://github.com/episphere/connect/issues/827), and follows [PR#508](https://github.com/episphere/connectFaas/pull/508).
> Fix email sending errors bounced from SendGrid

- utils/shared.js
Tighten up existing timestamp validation to match length.
Vijay found the long-running validation had a flaw:
Previous RegExp: const validIso8601Format = /\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z/;
The expected date format: 2023-11-07T18:58:38.901Z
But this was passing the check when it should have been failing: 2022233-01-10T09:44:00.033Z
The new version enforces start and end (overall length).
> more restrictive timestamp validation

- utils/sites.js
Add null handling for numeric values submitted through the API.
Case: regular numbers (not ConceptIDs) being submitted.
> fix numeric validation error

- updateParticipantData.json
- utils/shared.js
- utils/sites.js
hotfix: Gitter issue - Array validation for variables
173836415.266600170.110349197 and
173836415.266600170.543608829
I wasn't aware of these arrays when updating validation methods in updateParticipantData API.
> updateParticipantData array validation

- utils/events.js
- utils/fieldToConceptIdMapping.js
- utils/firestore.js
- utils/notifications.js
- utils/shared.js
* https://github.com/episphere/connect/issues/877
-----
* With the new PROMIS QOL Survey being added to the study we need to add logic into the API to accept responses from this survey and store them appropriately. We also need to mark participants as eligible for this survey once they first get an email or text 
-----
* Added PROMIS collection to list of Firestore collections to be backed up in `events.js`
* Added module status Concept IDs to `fieldToConceptIdMapping.js`
* Added function `updateSurveyEligiblity()` to mark a participant's status on a survey from `Not Yet Eligible` to `Not Yet Started`
* Added default variable for PROMIS Module Status to `shared.js`
* Added value for PROMIS survey to `moduleConceptsToCollections`, …
> PROMIS Survey Updates (API)

- utils/firestore.js
Related: https://github.com/episphere/connect/issues/755
Optimize reports data
• update searchSpecimenBySiteAndBoxId to handle more collectionIDs (for new big shipping boxes)
• use snapshot.count().get() for reports pagination. This counts docs and returns an integer instead of pulling all data and counting the length. Cost = 1 read per 1000 docs instead of 1 read per doc, data usage drastically reduced.
This merges with: https://github.com/episphere/biospecimen/pull/663
> biospecimen reports

- utils/connectApp.js
- utils/firestore.js
- utils/submission.js
Related: https://github.com/episphere/connect/issues/906
(1) Fetch sha value based on module, commit history, and survey start timestamp. This keeps survey versioning aligned for participants.
(2) update `retrieveUserSurveys` for parallel fetching (performance improvement).
EDIT: (3) Search raw text at the time of commit (based on sha value) to retrieve the correct version number for the module.
> fetch sha (commit history) for survey data

- utils/firestore.js
- utils/webhook.js
This PR addresses issue https://github.com/episphere/connect/issues/828
Change:
- Updated function `processSendGridEvent` for updating the sendgrid webhook data to notifications collection instead of sendgridTracking collection
- Created fucntion `processMergingSendGridData` for merging all the old data from sendgridTracking collection into notifications collection
Note:
- After merging all the old data from sendgridTracking collection into notifications collection, we will remove this code and the sendgridTracking collection in firestore as well.
> [#I828] Sendgrid Data Merge to Notifications Collection Table 

- utils/promis.js
* https://github.com/episphere/connect/issues/870
-----
* The wrong Concept ID was used in the configuration file for PROMIS Scoring
-----
* Updated constant in `promis.js`
> Fixed PROMIS Scoring CID

- utils/firestore.js
- utils/notifications.js
- utils/sites.js
Updates in this PR:
- Implement requests in [issue #930](https://github.com/episphere/connect/issues/930)
- Print count of updated participant documents before finishing `updateParticipantData`, for troubleshooting in future
> Allow a notification spec run only once per day

- utils/biospecimen.js
- utils/firestore.js
Related: https://github.com/episphere/connect/issues/960
•Update sorting order for Home Collections 'Assign Kits'
•Use .select() to pull less data
•Update naming conventions
•Add TODOs for future enhancements (this was a late addition, and future enhancements require coordination with the Biospecimen team)
> update sorting for Home Collections 'Print Labels' and 'Assign Kits'

- utils/notifications.js
This PR follows [PR #575](https://github.com/episphere/connectFaas/pull/575), to simplify SQL queries when using ISO time string as primary field.
> Simplify SQL query

- updateParticipantData.json
* N/A
-----
* KP needs to update the Concept ID `512820379` for 562 participants and it was decided the best way to do so was temporarily update the rules for the Update Participant Data API
-----
* Added rule to `updateParticipantData.json`
> KP Prod Change 051024

- utils/firestore.js
Changed kit receipt logic to:
1. Run in a transaction to prevent the risk of partial data updates in error cases
2. Validate that the Collection ID matches the Collection ID (Cup ID) that was linked to the Return Kit Tracking Number during Kit Assembly
> Kit receipt validation

- utils/firestore.js
- utils/shared.js
This PR adds logs showing counts of retrieved documents from Firestore, as described in [issue 1016](https://github.com/episphere/connect/issues/1016). Some code clean-ups are also done.
> Print retrieved documents counts

- utils/biospecimen.js
- utils/firestore.js
Validation work to prevent duplicate tracking numbers, per [1038](https://github.com/episphere/connect/issues/1038). Requires corresponding biospecimen work for full functionality.
> Duplicate tracking numbers now prohibited (1038)

- utils/connectApp.js
- utils/submission.js
Related: Quest 2.0 improvements
https://github.com/episphere/connect/issues/1066
• Fetch survey data (questionnaire repo) from GitHub API with an authenticated request.
This should be more robust than using the raw file fetch and should eliminate response code 0 errors.
Note: Merge with ConnectApp PR: https://github.com/episphere/connectApp/pull/811
> fetch survey modules through GitHub  API (authenticated)

- utils/firestore.js
* 
-----
* GCP alerted us that defaulting that would take place with Cloud Functions going to V2 instead of V1. Because of this, we need to update our import statement of `functions-framework` in order to reference the correct SDK.
-----
* Updated `require` statement in `firestore.js`
> Update Functions Framework Call

- utils/firestore.js
- utils/shared.js
This pull request addresses the following links:
- https://github.com/episphere/connect/issues/1063
Requests from issue:
- change query to get eligible home mouthwash kit participants using `desc` order (newest first)
- create 5 day lag for eligible home mouthwash kit participants to appear in query (Exclude eligible participants with `bloodOrUrineCollectedTimestamp` (740582332) within range from today's current date to 5 days before today's current date )
- Filter out P.O. Box in Address Line 1 (521824358)
Code Changes: 
- added a 'desc' argument to change OrderBy clause
- created `getFiveDaysAgoDateISO ` function and added another `where` clause to remove eligible participants with a bloodOrUrineCollectedTimestamp of five days or less than the current date.
- added …
> Issue#1063 - home mouthwash collection query and 5 day lag

- utils/bigquery.js
- utils/notifications.js
Temporarily add hard-coded 45-day restriction on MC survey reminders, to fix prod issue.
A long-term solution will be implemented shortly in September release.
> Block MC reminder after 45 days

- config/prod/cloudbuild1.yaml
- index.js
- utils/firestore.js
* N/A
-----
* Undiscovered bug when PROMIS survey was released prevented scoring API from being called when participants completed the survey
* Need to manually trigger these results to get processed
* Due to API being behind firewall we need a temporary end-point that can access the API when called from a local source
-----
*
> temp endpoint

- utils/biospecimen.js
- utils/firestore.js
- utils/notifications.js
Details of this PR:
- Print more detailed info when an error occurs when sending instant notifications, for easier troubleshooting
- Send status code 204 to Twilio after handling incoming messages, so that it doesn't complain with error 11200
> Updated error handling in instant notifications

- utils/biospecimen.js
- utils/firestore.js
- utils/notifications.js
- utils/webhook.js
Details of this PR:
-Print more detailed info when an error occurs when sending instant notifications, for easier troubleshooting
-Send status code 204 to Twilio after handling incoming messages, so that it doesn't complain with errors  12300 or 11200
> Error handling prod

- utils/connectApp.js
- utils/firestore.js
- utils/shared.js
- utils/submission.js
Related: https://github.com/episphere/connect/issues/1168 
Update the submit endpoint to await the response and return a response for all cases.
Implementation: This is used for response confirmation, in-app handling & communication, and question reversion when a response to a question fails to update server-side in Quest 2.
> await response from 'submit' endpoint

- utils/submission.js
Noticed bug in `getFilteredParticipants` while creating Postman examples, need to move check for `req.query.type` after the instantiation of `helpMessage`
Also updating return code in `req.status` for consistency.
> API Refactor

- utils/shared.js
Prevents overwriting of additional biospecimen-related keys on participants once set. (Follow-up to [1062](https://github.com/episphere/connect/issues/1062) testing)
> 1062 Followup

- test/test.js
- utils/firestore.js
Home mouthwash kit now defaults to physical address if provided at all, vs. only when mailing address is a PO Box, as per notes on [1174](https://github.com/episphere/connect/issues/1174).
> 1174 followup

- utils/firestore.js
The PR is related to:
- https://github.com/episphere/connect/issues/1248
Original filter does not handle spacing after "p" for po box.
Code Change:
- added optional spacing after the P for regex matching
> Update p.o. box filter for assign kits

- utils/firestore.js
- utils/submission.js
Fixed an issue with an include in the wrong place in submit endpoint
Fixed an issue where replacement home MW CSV wouldn't print if there were no first replacement kits in the queue
> Quick fixes

- utils/firestore.js
Fixed an issue where marking replacement kits as undeliverable would update the initial kit and not the replacement kit.
Local testing confirmed that correct flag was updated for participant with initial kit, first replacement kit, and second replacement kit.
> Undeliverable fix for replacement kits

- utils/firestore.js
Fixes an issue where the shippedDateTime received from shippedKitStatusParticipants was always the shipped time for the initial kit, even for R1 and R2 kits.
> Kit Shipped Date Display Fix

- utils/firestore.js
Backend work for [1302](https://github.com/episphere/connect/issues/1302). queryKitsByReceivedDate now finds the kitLevel, E.G. whether the kit is an initial kit, a first replacement kit or a second replacement kit, and passes it along. Because that data lives only in the associated kitAssembly record, this now involves querying related kits.
> queryKitsByReceivedDate now finds and passes back kitLevel

- utils/biospecimen.js
- utils/firestore.js
Fixes error handling for add and update kit data to be consistent with expectations and handling in biospecimen. This change was made as a part of the cleanup work for [1133](https://github.com/episphere/connect/issues/1133) after realizing that several errors were not being returned as expected from the API. Changes:
firestore.js:
* Errors from addKitAssemblyData and updateKitAssemblyData are now thrown and not returned, preventing messages from being swallowed
biospecimen.js
* error cases in corresponding endpoints to above now return errors with explicit correct object formatting and account for possible lack of error.message
Tests done:
* Automatic tests re-run
* Tested reused kit IDs and tracking numbers on kitAssembly page and ensured that errors displayed correctly.
> Fixes error handling for add and update kit data to be consistent with expectations and handling in biospecimen. 

- utils/connectApp.js
- utils/dhq.js
- utils/fieldToConceptIdMapping.js
Related: https://github.com/episphere/connect/issues/1238
• Add handling for DHQ External survey status variable (QC check).
• Add return statements to the Cloud Run function. I found the return wasn't implicit, so it was timing out in Cloud Scheduler.
> DHQ ConnectFaas testing updates

- utils/dhq.js
- utils/fieldToConceptIdMapping.js
Map DHQ survey status (internal) to DHQ survey status (external)
Related: https://github.com/episphere/connect/issues/1238
We're using a different set of Concept IDs to refer to DHQ survey status found in the DHQ back end. This updates survey status mapping to use those variables.
> Map DHQ survey status (internal) to DHQ survey status (external)

- utils/firestore.js
Fixes an issue where getKitsByReceivedDate would error if no kits received on the given date were found
Resolves an issue where errors in queryCountReplacementHomeCollectionAddressesToPrint were being swallowed and resulting in false 200 responses.
Changes:
* queryCountReplacementHomeCollectionAddressesToPrint no longer returns Error, as location calling it expects errors to be thrown. Try/catch block around this logic removed, as it is unnecessary.
* queryCountReplacementHomeCollectionAddressesToPrint checks for empty arrays before attempting to run IN query.
* queryCountReplacementHomeCollectionAddressesToPrint also runs a sanity check that unique kit ID exists before trying to use it as a key.
> Prod error fix

- test/test.js
- utils/dashboard.js
- utils/firestore.js
- utils/shared.js
Backend support for issue [1020](https://github.com/episphere/connect/issues/1020) - "Add 'Request a Kit' button on the SMDB (Biospecimen) - Part A"
Changes:
shared.js:
* getHomeMWReplacementKitData renamed to getHomeMWKitData to better reflect new functionality
* getHomeMWKitData now requests an initial kit when it receives a participant who has not yet been marked as eligible for an initial kit.
* Some firming up of existence checking when reading nested properties of objects.
dashboard.js
* requestHomeKit endpoint added
* getHomeMWReplacementKitData -> getHomeMWKitData rename reflected
firestore.js
* getHomeMWReplacementKitData -> getHomeMWKitData rename reflected
* queryHomeCollectionAddressesToPrint sorting updated to place manually requested replacement kits at the top of the list
* …
> 1020 support

- utils/firestore.js
Code change: Updated the query where conditions in queryCountHomeCollectionAddressesToPrint to ensure they match the query conditions in queryHomeCollectionAddressesToPrint. (Follow-up to [a comment on 1020 testing](https://github.com/episphere/connect/issues/1020#issuecomment-2960171612))
> Fixed an issue with the count of addresses to print not matching the addresses available to print.

- utils/dashboard.js
Related: https://github.com/episphere/connect/issues/1327
Rm updateDHQReportViewedStatusendpoint from dashboard.js. We will only update the report viewed status from participant actions in the PWA, so we don't use this endpoint in dashboard.js.
> Clean-up: Rm updateDHQReportViewedStatus from dashboard.js

- utils/firestore.js
- utils/incentive.js
* https://github.com/episphere/connect/issues/1222
-----
* Updated `retrieveParticipantsEligibleForIncentives()` to utilized `startAfter()` functionality
* Updated `eligibleForIncentive` API end-point to absorb `cursor` parameter
> Re-Implement Remove Offset Functionality (Continued)

- test/test.js
- utils/fileUploads.js
- utils/shared.js
For [1306](https://github.com/episphere/connect/issues/1306)
Changes:
shared.js:
* Updated getHomeMWKitData behavior to handle addressUndeliverable by changing the status to initialized, according to the new behavior specified in test.js:
* Updated getHomeMWKitData tests to reflect new behavior for undeliverable addresses fileUploads.js:
* Added an existence check to fix an issue that was preventing npm test from running when process.env.GCLOUD_PROJECT was not set
Testing:
* Updated and ran test.js
* Requested an initial kit for a participant with an undeliverable address for the initial kit and verified the data updated appropriately, including completing the kit receipt workflow
* Requested a replacement kit for the same participant, marked the address as undeliverable, re-requested a …
> 1306 Updates

- utils/fieldToConceptIdMapping.js
- utils/shared.js
This PR adds received time to cancer data before saving to `cancerOccurrence` collection in Firestore, as requested in [issue#1293](https://github.com/episphere/connect/issues/1293).
> Add received time of cancer data

- utils/validation.js
Participants who have already have baseline mouthwash collected will no longer be marked as home MW kit of initialized on clinical specimen submission
Changes:
validation.js
* processMouthwashEligibility now has an additional check for baselineMouthwashCollected not being equal to yes when determining eligibility
> 1374 support

- utils/firestore.js
This PR implements requirements in [issue#1353](https://github.com/episphere/connect/issues/1353), for data destruction daily cleanups. Details below:
- Delete pathology reports in bucket
- Delete docs in "pathologyReports" collection in Firestore
> Delete pathology reports and Firestore records

- utils/biospecimen.js
- utils/firestore.js
- utils/sites.js
- utils/submission.js
Updates different stages of the home MW kit process to appropriately handle deceased and withdrawn users at each point in time. For [1370](https://github.com/episphere/connect/issues/1370).
Changes:
biospecimen.js
* confirmShipment: Error changed to include error message as response (previous behavior returns error message under key message instead of response, leading to error being swallowed on front end)
site.js
* updateParticipantData now clears kit status for participants with home MW kits in the status of initialized or address undeliverable.
submission.js
* Cleared some commented out unused code for readability
firestore.js
* assignKitToParticipant now checks for deceased and withdrawn participants, clears their relevant kit status, and informs the user
* markParticipantAddress …
> 1370 updates

- test/integration/dhq.integration.test.js
- test/unit/dhq.test.js
- utils/dhq.js
- utils/firestore.js
Related: https://github.com/episphere/connect/issues/1329
•Sanitize DHQ report keys across all reports for BigQuery Sync compatibility.
•Update `dhqDetailedAnalysis` data structure: pre-flatten data to question-based format for BigQuery sync compatibility.
•Remove DHQ Data Destruction (holding for Aug 2025 release, details TBD).
•Update tests for key sanitization and new dhqDetailedAnalysis data structure.
Tests:
> Dhq phase3 BigQuery Compatibility

- utils/biospecimen.js
- utils/firestore.js
The [issue#1223 ](https://github.com/episphere/connect/issues/1223) is linked to 
- https://github.com/NCI-C4CP/biospecimen/pull/855
- https://github.com/episphere/connect/issues/1176
Request Changes:
-  refactor `getBoxesPagination()` using offset, to reduce and limit the costs of firebase reads
- Problem with offset, this approach still incurs a cost and reads the documents skipped
- Use [cursor](https://firebase.google.com/docs/firestore/query-data/query-cursors) instead as a marker for pagination
Code Changes:
- updated `getBoxesPagination()` function to accept paginationDirection
- added control flow using paginationDirection value and documentId markers to return shipped boxes
- added `try...catch` conditional endpoints
> Issue#1223 remove offset get boxes pagination

- utils/notifications.js
The retrieveNotifications will now only update the read status if requested via a query parameter
> Updated retrieveNotifications
